### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by zparcheta** [Stanford-Mobisocial-IoT-Lab/almond-nnparser#1]
Hello, 
Could you upload some example dataset? There should be only simple sentences or should have some specific format?
regards

**Comment by gcampax** [comment]
The format is tab separated.

The first column is the example ID, it could be anything, it's just to help look at the examples and figure out which work and which don't.
The second column is the sentence, in PTB tokenized format, with entities replaced.
The third column is the program, in linearized TT syntax. This changes from time to time as we need it, because different formats yield different quality models.
The fourth column is the binarized constituency parse. This is optional and used only if use the TreeEncoder.

The tsv file format is normally produced by
https://github.com/Stanford-Mobisocial-IoT-Lab/sempre/blob/master/src/edu/stanford/nlp/sempre/thingtalk/seq2seq/ExtractSeq2Seq.java
which consumes sentences/ThingTalk JSON format from a database.

We are not releasing the full dataset just yet, only a few example sentences.
