### ISSUE TITLE
missing file ~/almond-nnparser/scripts/prepare.sh

### ISSUE THREAD

**Issue by SeekPoint** [Stanford-Mobisocial-IoT-Lab/almond-nnparser#2]

**Comment by gcampax** [comment]
Hi, thank you for reporting this issue. I am afraid that this issue was reported against an older version of the software, and it is no longer relevant: the current version does not include a prepare.sh script, and makes no mention of it anywhere.
Please follow the new instructions in README.md if you wish to use genie-parser.
